### ISSUE TITLE
Is complex power correct

### ISSUE THREAD

**Issue by bjpalmer** [GridOPTICS/GridPACK#10]
The getComplexPower calculation looks like it might not be correct. Switching the from and to bus changes value.

**Comment by chenyousu** [comment]
It looks good to me. The value change in power is because of flow direction change as the power flow output only shows one direction (from -> to). If you switch the from/to, the flow value changes as the flow direction changes (and the line loss). It might be a good idea to show the power flow at both directions in  output.

**Comment by bjpalmer** [comment]
The current operation appears to be correct. I'm closing this issue.
