### ISSUE TITLE
Remove cmake-jedbrown and all related stuff

### ISSUE THREAD

**Issue by abhyshr** [GridOPTICS/GridPACK#112]
Now that we have moved to using `pkgconfig` for building PETSc in develop branch, can we delete all cmake-jedbrown files/submodules and anything associated with it? @bjpalmer @wperkins : Any of you willing to do this?

**Comment by wperkins** [comment]
@abhyshr, this definitely needs to be done, but I'm not sure of it's priority. There are a number of PETSc-related problems that need attention and quite a bit of work. There are several unit tests that are failing because of changes to PETSc semantics (#118).  The largest of these is replacement of GA-based dense matrix handling with whatever PETSc now provides natively (if we still need dense matrix manipulation, which I think we do, #117).  It also looks like GridPACK won't build with 3.18.x (#116).
