### ISSUE TITLE
How to configure and install PETSc for GridPACK?

### ISSUE THREAD

**Issue by pelesh** [GridOPTICS/GridPACK#16]
[Installation notes for GridPACK dependencies](https://www.gridpack.org/wiki/index.php/Software_Required_to_Build_GridPACK) do not provide example how to configure and install PETSc. The instructions there seem to be specific for Mac OS X, but it is not obvious how to modify them for a different platform. also, it seems too much of a burden is placed on user to figure out what PETSc configuration options are needed (such as adding ParMETIS support).

**Comment by wperkins** [comment]
I'm not sure I follow you. The intention of that page is to provide an overview of software required by GridPACK and the _GridPACK_ configuration options  used to specify those requirements.  At the top of that page, there is a list of specific platforms.  If you follow those, it will show you detailed PETSc configuration and build instructions specific to that platform.

**Comment by pelesh** [comment]
This page seems to be a bit misleading, because it does provide some dependency installation instructions and it is not obvious that user should ignore those (?) and look at the specific platform installation instructions instead. Just out of curiosity -- why not leave only the links to specific platform installation instructions on this page?

**Comment by bjpalmer** [comment]
For each package (Boost, GA, PETSc, etc.), I added links to specific scripts documented on different platforms. I can also add links to installation commands such as yum and apt-get.

**Comment by diaoruisheng** [comment]
I installed CENTOS and UBUNTU versions without any issues. you should follow the instructions for the corresponding operating systems and the example config files can be found there. for example, if you want to install a CENTOS version, go to: https://www.gridpack.org/wiki/index.php/Building_on_CentOS6

the PETSC config file can be found there:

PETSc, version 3.6.4
For some reason, more recent PETSc versions were not recognized by the GridPACK CMake configuration, possibly because of the older compiler. This version appears to work. The script below should be run in the top level PETSc directory. The PETSc libraries and include files will end up in a directory under the top level directory with name of the PETSC_ARCH variable. This build assumes that the top level PETSc directory is located at /home/admin/Desktop/software/petsc-3.6.4. You will need to modify this directory to reflect your own system. The PETSC_ARCH variable can be set to whatever string you want. 
   python ./config/configure.py \
       PETSC_ARCH=linux-gnu44-complex-opt \
       --with-mpi=1 \
       --with-cc="mpicc" \
       --with-fc="mpif90" \
       --with-cxx="mpicxx" \
       --with-c++-support=1 \
       --with-c-support=0 \
       --with-fortran=1 \
       --with-scalar-type=complex \
       --with-precision=double \
       --with-clanguage=c++ \
       --with-fortran-kernels=generic \
       --with-valgrind=0 \
       --download-superlu_dist \
       --download-superlu \
       --download-parmetis \
       --download-metis \
       --download-suitesparse \
       --download-f2cblaslapack=1 \
       --download-mumps=0 \
       --download-scalapack=0 \
       --with-shared-libraries=0 \
       --with-x=0 \
       --with-mpirun=mpiexec \
       --with-mpiexec=mpiexec \
       --with-debugging=0

**Comment by sl4ven** [comment]
@diaoruisheng The point of this issue is exactly what you stated -- user should follow the instructions for specific platform. The [dependencies page](https://www.gridpack.org/wiki/index.php/Software_Required_to_Build_GridPACK) is misleading as it provides partial installation instructions for all dependencies, which are not very helpful for an average user. It might be better to only list GridPACK dpendencies on this page and refer user to specific platform instructions for information how to obtain and install all the dependencies.

**Comment by pelesh** [comment]
@diaoruisheng The point of this issue is exactly what you stated -- user should follow the instructions for specific platform. The [dependencies page](https://www.gridpack.org/wiki/index.php/Software_Required_to_Build_GridPACK) is misleading as it provides partial installation instructions for all dependencies, which are not very helpful for an average user. It might be better to only list GridPACK dpendencies on this page and refer user to specific platform instructions for information how to obtain and install all the dependencies.

**Comment by diaoruisheng** [comment]
to be honest, I'm not sure if Mac is a good platform to test GridPACK, as it targets at students, researchers and engineers in the power community where Windows is still the dominating OS for many  grid planning and operational studies, at least in North America.   Should GridPACK be more focused on one or two specific platforms like Linux Ubuntu or CENTOS and provide much deeper support like adding all kinds of fancy functions to push it towards a higher maturity level?    just my 2 cents.

**Comment by wperkins** [comment]
I think this should be closed.  I think there are plenty of examples of how to build PETSc on a variety of platforms.
