### ISSUE TITLE
Non-expert installation instructions should not suggest changing environment variables

### ISSUE THREAD

**Issue by pelesh** [GridOPTICS/GridPACK#31]
Installation instructions for [RHEL 7](https://www.gridpack.org/wiki/index.php/Building_on_RHEL) and [Ubuntu 16.04](https://www.gridpack.org/wiki/index.php/Building_on_Ubuntu) suggest setting environment variables `CC` and `CXX`. This is not needed since GridPACK can be built with the default compiler on those systems. Beside, in the instructions, the environment variables are set to system default values, so they will have no effect anyways. This seems to be more of a distraction than a help for a novice user. 

Also, [RHEL 7](https://www.gridpack.org/wiki/index.php/Building_on_RHEL) instructions suggest setting environment variables to set compiler flags. It is probably better to specify compiler flags at build configuration for each dependency and GridPACK, especially since some of the dependencies will ignore those environment variables at the configuration stage.

Setting environment variables should be reserved for expert level Linux installation and only if needed.

**Comment by wperkins** [comment]
On all the platforms I work with, it's possible to have multiple compiler sets and MPI implementations installed, and my systems do. In my experience with CMake, I've found that it works very hard to use the wrong compiler.   Often its choice will leave me scratching my head and asking "Why on earth would that be the first choice?".  It's caused me pain, so, in the build instructions I've written, I try to warn about it. 
I think setting a perhaps unnecessary environment variable is better than dealing with the mysterious behavior that happens when the wrong compiler is chosen by CMake
A novice Linux user will need to quickly learn about environment variables anyway.

**Comment by bjpalmer** [comment]
I've had similar problems where including explicit definitions of compilers has been necessary to get builds to work. I think it is better to have users include some possibly unnecessary definitions than to have the build fail for mysterious and unintelligible reasons.

**Comment by bjpalmer** [comment]
I'm closing this issue. If there are violent objections, we can reopen it.
