### ISSUE TITLE
MacOS -- Add Powerflow example

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#48]
Broken out sub-issue from #26. After installing MacOS from scratch, a unit test is run, but no application example is given. The example given in the Ubuntu Package install should be included here as well.

**Comment by wperkins** [comment]
Rather than repeating a bunch of stuff on _every_ platform page, I add a section,  ["Running the Powerflow Example(s)"](https://www.gridpack.org/wiki/index.php/How_to_Build_GridPACK#Running_the_Powerflow_Example.28s.29) to the general [building](https://www.gridpack.org/wiki/index.php/How_to_Build_GridPACK) page.   
I added links to the [GridPACK](https://www.gridpack.org/wiki/index.php/Building_on_Mac_High_Sierra#GridPACK) part of the [Mac OS build page](https://www.gridpack.org/wiki/index.php/Building_on_Mac_High_Sierra). 

See if this helps.
