### ISSUE TITLE
make test stuck at Start 40: complex_dae_solver_serial

### ISSUE THREAD

**Issue by yhwu** [GridOPTICS/GridPACK#9]
Hi,

I wrote a script to build gridpack. It proceeded almost to the end except tests stuck at complex_dae_solver_serial. I'd appreciate if you could take a look and help me to get it through. The script is available from 

https://github.com/yhwu/misc/blob/master/gridpack_installation.sh

and it takes a few minutes to get to the tests. 

Thanks!
Yinghua

**Comment by wperkins** [comment]
Yinghua,
Can you supply some information about your system: OS, MPI, compilers, etc.?
I would recommend that you avoid bleeding edge PETSc and GA.  Use released versions. Significant things change on a whim, especially with PETSc.  E.g., I've had trouble with PETSc 3.8 because they've changed the C++ interface.   GA 3.6.2 and PETSc 3.7.6 are the latest I've used successfully.  
Don't build GridPACK in `cmake-modules`.  Make a new, empty directory instead.  This makes it easier to do a clean build.
So the complex_dae_solver_serial doesn't time out?  If it is hanging, the test should time out after 20 seconds (you set this).  
What happens when you run the test by hand? In the your build directory (`cmake-modules`), 
```
cd math
./complex_dae_solver_test
mpiexec -np 2 complex_dae_solver_test
```

Thanks.
Bill

**Comment by bjpalmer** [comment]
Bill,

Did you mean GA 5.6.2?

Bruce

**Comment by wperkins** [comment]
Yes.  GA 5.6.2.

**Comment by yhwu** [comment]
After I rolled back to PETSc 3.6.4, GA 5.6.2, and GridPACK release 3.1, all tests passed. The current commit of master branch failed contingency_analysis_parallel test. I am using Ubuntu 16.04, openmpi, GNU compilers inside vmware workstation. I have updated my installation script. Next, will try on MISO state estimator.

Thank you so much!
Yinghua

**Comment by bjpalmer** [comment]
The failure with contingency_analysis_parallel test has been there for a while. We haven’t been able to figure out why that fails in make test. If you run it separately, it seems to work fine.

**Comment by wperkins** [comment]
You should be good to go. 
We too are having trouble with `contingency_analysis_parallel` test. It passes on some systems, fails on others. Try running it with 2 processors instead of 4 (`-D MPIEXEC_MAX_NUMPROCS:STRING="2"`).     That works on my Ubuntu system.  
On Ubuntu 16.04, you can use the GA package (llibga-dev, version 5.3+dfsg-1 on my system). You need to add  
```
-D GA_EXTRA_LIBS:STRING="-lscalapack-openmpi -lblacsCinit-openmpi -lblacs-openmpi -llapack -lblas -lgfortran"
```
to your CMake command line.  That would save you a little building.  I'm working on building GridPACK with the Ubuntu PETSc package (libpetsc3.6.2-dev:amd64, version 3.6.2.dfsg1-3ubuntu1) which uses MUMPS and not SuperLU_dist for a parallel LU solver.  GridPACK currently expects SuperLU_dist to be part of PETSc for the unit tests to pass.
