### ISSUE TITLE
Parser for PSSE v34

### ISSUE THREAD

**Issue by abhyshr** [GridOPTICS/GridPACK#99]
Unfortunately, the v33 parsers in GridPACK do not work for v34 files. There are some incompatible changes in v34 as a result of which v34 raw files cannot be parsed correctly by v33 parsers.

**Comment by abhyshr** [comment]
@yliu250
@chenyousu

**Comment by bjpalmer** [comment]
I will need some documentation to figure out how to set up a v34 parser. If there is significant overlap between v33 and v34, it would probably be a good idea to restructure the v33 parser so that large parts of it can be used in v34. The basic idea would be to pull out the parsers for individual blocks into separate files and just leave a driver that combines the blocks into an overall parser for v33, v34, etc. That way if the formatting of a block doesn't change between versions, you can just reuse it.

This change would make the structuring of the raw file parsers similar to the dyr file parser.

**Comment by bjpalmer** [comment]
The restructuring of the parsers was completed and used to implement v34 and v35 parsers. Closing this issue.

**Comment by bjpalmer** [comment]
Closing.
